services:
  base: &base
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    networks:
      - wiza_network

  bot:
    <<: *base
    command: ["python", "./bot.py"]

  worker:
    <<: *base
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis

  flower:
    <<: *base
    command: ["celery", "-A", "tasks", "flower", "--port=5555"]
    depends_on:
      - redis
    ports:
      - "5555:5555"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - wiza_network

networks:
  wiza_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
