services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    env_file: .env
    networks:
      - wiza_network

  bot:
    image: app:latest
    command: ["python", "./bot.py"]
    depends_on:
      - redis
    networks:
      - wiza_network

  worker:
    image: app:latest
    command: ["celery", "-A", "src.tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - wiza_network

  flower:
    image: app:latest
    command: ["celery", "-A", "src.tasks", "flower", "--port=5555"]
    depends_on:
      - redis
    ports:
      - "5555:5555"
    networks:
      - wiza_network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - wiza_network

networks:
  wiza_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
