services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    command: ["python", "./bot.py"]
    env_file: .env
    depends_on:
      - redis
    networks:
      - vnet

  worker:
    image: app:latest 
    command: ["celery", "-A", "src.tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
    networks:
      - vnet

  flower:
    image: app:latest
    command: ["celery", "-A", "src.tasks", "flower", "--port=5555"]
    depends_on:
      - redis
    ports:
      - "5555:5555"
    networks:
      - vnet

  redis:
    image: redis:alpine
    restart: always
    networks:
      - vnet

networks:
  vnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.150.0/24
